package chatapp;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.util.Locale;
import java.util.ResourceBundle;

public class ChatAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChatAppFrame
     * @param language
     */
    public ChatAppFrame(String language) {
        initComponents();
        setLanguage(language);
    }

    public void setLanguage(String lang){
        if(lang.equalsIgnoreCase("English")){
            Locale.setDefault(new Locale("en", "US"));
        }else if(lang.equalsIgnoreCase("Korean")){
            Locale.setDefault(new Locale("ko", "KR"));
        }else{
            Locale.setDefault(new Locale("ja", "JP"));
        }
        
        ResourceBundle r = ResourceBundle.getBundle("chatapp/chatapp");
        jLabel5.setText(r.getString("languageLabel"));
        jLabel1.setText(r.getString("puidLabel"));
        jLabel2.setText(r.getString("msgLabel"));
        jLabel3.setText(r.getString("puidLabel"));
        jLabel4.setText(r.getString("msgLabel"));
        sendButton.setText(r.getString("sendButton"));
        receiveButton.setText(r.getString("receiveButton"));
        switchButton.setText(r.getString("switchButton"));
        clearButton.setText(r.getString("clearButton"));
        jMenu1.setText(r.getString("msgLabel"));
        menuSend.setText(r.getString("sendButton"));
        menuReceive.setText(r.getString("receiveButton"));
        menuEnd.setText(r.getString("endButton"));
        jMenu2.setText(r.getString("windowLabel"));
        menuClearMessage.setText(r.getString("clearMsgButton"));
        menuClearBox.setText(r.getString("clearChatButton"));
        menuSwitchUser.setText(r.getString("switchButton"));
        tabs.setTitleAt(0, r.getString("user1Label"));
        tabs.setTitleAt(1, r.getString("user2Label"));
    }
    
    Message message = new Message();
    File log = new File("/Users/v/Desktop/CNIT 32500/Lab 04/log.txt");
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idBox1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        messageBox1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        idBox2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        messageBox2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        receiveButton = new javax.swing.JButton();
        switchButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        changeButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuSend = new javax.swing.JMenuItem();
        menuReceive = new javax.swing.JMenuItem();
        menuEnd = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuClearMessage = new javax.swing.JMenuItem();
        menuClearBox = new javax.swing.JMenuItem();
        menuSwitchUser = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Receiver PUID: ");

        jLabel2.setText("Message:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageBox1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(messageBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("User 101", jPanel1);

        jLabel3.setText("Receiver PUID: ");

        jLabel4.setText("Message:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messageBox2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(messageBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabs.addTab("User 999", jPanel3);

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        receiveButton.setText("Receive");
        receiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiveButtonActionPerformed(evt);
            }
        });

        switchButton.setText("Switch User");
        switchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Choose Language:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Korean", "Japanese" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        changeButton.setText("Change");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Message");

        menuSend.setText("Send Message");
        menuSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSendActionPerformed(evt);
            }
        });
        jMenu1.add(menuSend);

        menuReceive.setText("Receive Message");
        menuReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReceiveActionPerformed(evt);
            }
        });
        jMenu1.add(menuReceive);

        menuEnd.setText("End Chat");
        menuEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEndActionPerformed(evt);
            }
        });
        jMenu1.add(menuEnd);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Window");

        menuClearMessage.setText("Clear Message Box");
        menuClearMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearMessageActionPerformed(evt);
            }
        });
        jMenu2.add(menuClearMessage);

        menuClearBox.setText("Clear Chat Box");
        menuClearBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearBoxActionPerformed(evt);
            }
        });
        jMenu2.add(menuClearBox);

        menuSwitchUser.setText("Switch User");
        menuSwitchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSwitchUserActionPerformed(evt);
            }
        });
        jMenu2.add(menuSwitchUser);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(sendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(receiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(switchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(changeButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeButton))
                .addGap(33, 33, 33)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sendButton)
                    .addComponent(receiveButton)
                    .addComponent(clearButton)
                    .addComponent(switchButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0){
            LocalDateTime ldt = LocalDateTime.now();
            String UserID = tabs.getTitleAt(tabs.getSelectedIndex());
            message.setMessage(ldt + " - " + UserID + ": " + messageBox1.getText() + "\n");
            message.setPerson(new Person(UserID));
            message.sendMessage();
            String text = ldt + " - " + UserID + ": " + messageBox1.getText();
            jTextArea1.append("\n" + text + "\n");
            try{
                FileWriter fw = new FileWriter(log, true);
                fw.write(text + "\n");
                fw.close();
            }catch(Exception e){
                e.printStackTrace();
            }finally{
                messageBox1.setText("");
            }
        }else if(tabs.getSelectedIndex() == 1){
            LocalDateTime ldt = LocalDateTime.now();
            String UserID = tabs.getTitleAt(tabs.getSelectedIndex());
            message.setMessage(ldt + " - " + UserID + ": " + messageBox2.getText() + "\n");
            message.setPerson(new Person(UserID));
            message.sendMessage();
            String text = ldt + " - " + UserID + ": " + messageBox2.getText();
            jTextArea2.append("\n" + text + "\n");
            try{
                FileWriter fw = new FileWriter(log, true);
                fw.write(text + "\n");
                fw.close();
            }catch(Exception e){
                e.printStackTrace();
            }finally{
                messageBox2.setText("");
            }
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void menuClearMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearMessageActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            messageBox1.setText("");
        else if(tabs.getSelectedIndex() == 1)
            messageBox2.setText("");
    }//GEN-LAST:event_menuClearMessageActionPerformed

    private void switchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchButtonActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            tabs.setSelectedIndex(1);
        else if(tabs.getSelectedIndex() == 1)
            tabs.setSelectedIndex(0);
    }//GEN-LAST:event_switchButtonActionPerformed

    private void menuSwitchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSwitchUserActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            tabs.setSelectedIndex(1);
        else if(tabs.getSelectedIndex() == 1)
            tabs.setSelectedIndex(0);
    }//GEN-LAST:event_menuSwitchUserActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            messageBox1.setText("");
        else if(tabs.getSelectedIndex() == 1)
            messageBox2.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void menuClearBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearBoxActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            jTextArea1.setText("");
        else if(tabs.getSelectedIndex() == 1)
            jTextArea2.setText("");
    }//GEN-LAST:event_menuClearBoxActionPerformed

    private void menuSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSendActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0){
            LocalDateTime ldt = LocalDateTime.now();
            String UserID = tabs.getTitleAt(tabs.getSelectedIndex());
            message.setMessage(ldt + " - " + UserID + ": " + messageBox1.getText() + "\n");
            message.setPerson(new Person(UserID));
            message.sendMessage();
            String text = ldt + " - " + UserID + ": " + messageBox1.getText();
            jTextArea1.append(text + "\n");
            try{
                FileWriter fw = new FileWriter(log, true);
                fw.write("\n" + text + "\n");
                fw.close();
            }catch(Exception e){
                e.printStackTrace();
            }finally{
                messageBox1.setText("");
            }
        }else if(tabs.getSelectedIndex() == 1){
            LocalDateTime ldt = LocalDateTime.now();
            String UserID = tabs.getTitleAt(tabs.getSelectedIndex());
            message.setMessage(ldt + " - " + UserID + ": " + messageBox2.getText() + "\n");
            message.setPerson(new Person(UserID));
            message.sendMessage();
            String text = ldt + " - " + UserID + ": " + messageBox2.getText();
            jTextArea2.append(text + "\n");
            try{
                FileWriter fw = new FileWriter(log, true);
                fw.write("\n" + text + "\n");
                fw.close();
            }catch(Exception e){
                e.printStackTrace();
            }finally{
                messageBox2.setText("");
            }
        }
    }//GEN-LAST:event_menuSendActionPerformed

    private void receiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiveButtonActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            jTextArea1.append(message.receiveMessage());
        else if(tabs.getSelectedIndex() == 1)
            jTextArea2.append(message.receiveMessage());
    }//GEN-LAST:event_receiveButtonActionPerformed

    private void menuReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReceiveActionPerformed
        // TODO add your handling code here:
        if(tabs.getSelectedIndex() == 0)
            jTextArea1.append(message.receiveMessage());
        else if(tabs.getSelectedIndex() == 1)
            jTextArea2.append(message.receiveMessage());
    }//GEN-LAST:event_menuReceiveActionPerformed

    private void menuEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEndActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuEndActionPerformed

    String lang;
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        lang = jComboBox1.getSelectedItem().toString();
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        // TODO add your handling code here:
        lang = jComboBox1.getSelectedItem().toString();
        //this.applyComponentOrientation();
        //new ChatAppFrame(lang).setVisible(true);
        if(lang.equalsIgnoreCase("English")){
            this.setLocale(new Locale("en", "US"));
        }else if(lang.equalsIgnoreCase("Korean")){
            this.setLocale(new Locale("ko", "KR"));
        }else if(lang.equalsIgnoreCase("Japanese")){
            this.setLocale(new Locale("ja", "JP"));
        }
        //this.setLocale();
        ResourceBundle r = ResourceBundle.getBundle("chatapp/chatapp");
        jLabel5.setText(r.getString("languageLabel"));
        jLabel1.setText(r.getString("puidLabel"));
        jLabel2.setText(r.getString("msgLabel"));
        jLabel3.setText(r.getString("puidLabel"));
        jLabel4.setText(r.getString("msgLabel"));
        sendButton.setText(r.getString("sendButton"));
        receiveButton.setText(r.getString("receiveButton"));
        switchButton.setText(r.getString("switchButton"));
        clearButton.setText(r.getString("clearButton"));
        jMenu1.setText(r.getString("msgLabel"));
        menuSend.setText(r.getString("sendButton"));
        menuReceive.setText(r.getString("receiveButton"));
        menuEnd.setText(r.getString("endButton"));
        jMenu2.setText(r.getString("windowLabel"));
        menuClearMessage.setText(r.getString("clearMsgButton"));
        menuClearBox.setText(r.getString("clearChatButton"));
        menuSwitchUser.setText(r.getString("switchButton"));
        tabs.setTitleAt(0, r.getString("user1Label"));
        tabs.setTitleAt(1, r.getString("user2Label"));
        this.repaint();
    }//GEN-LAST:event_changeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatAppFrame("English").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField idBox1;
    private javax.swing.JTextField idBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JMenuItem menuClearBox;
    private javax.swing.JMenuItem menuClearMessage;
    private javax.swing.JMenuItem menuEnd;
    private javax.swing.JMenuItem menuReceive;
    private javax.swing.JMenuItem menuSend;
    private javax.swing.JMenuItem menuSwitchUser;
    private javax.swing.JTextField messageBox1;
    private javax.swing.JTextField messageBox2;
    private javax.swing.JButton receiveButton;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton switchButton;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
